services:
  indexer:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/postgres?options=--search_path%3Dpublic
      - REMOTE_STORE_URL=${REMOTE_STORE_URL}
      - RUST_LOG=info
      - START_CHECKPOINT=${START_CHECKPOINT}
       # Add these new environment variables to reduce db frictions
      - PIPELINE_BLOBS_BATCH_SIZE=10  # Reduce batch size for blobs pipeline
      - PIPELINE_BLOBS_WORKERS=1      # Reduce number of workers for blobs pipeline
      - PIPELINE_BLOBS_RETRY_DELAY_MS=1000
      - LOCAL_MODE=${LOCAL_MODE}
      - CHECKPOINT_DIR=${CHECKPOINT_DIR}
      - PACKAGE_ADDRESS=${PACKAGE_ADDRESS}  # This will use the environment variable from your shell


